baseURL = "http://scott.maclure.info/tech/"
languageCode = "en-us"
title = "Scott Maclure's Tech Blog"
theme = "hello-friend-ng"
paginate = 10
publishdir = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Tech blog for a Cloud consultant."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My tech blog"
  keywords = "blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/scott-maclure/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/scottmaclure/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Scott's Test Blog"
    subtitle = "A tech blog from a Cloud consultant"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Scott's Tech Blog"
      logoHomeLink = "/tech/posts"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "https://scott.maclure.info/cv/"
